apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rs-cpu-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: rs-cpu-service 
  endpoints:
  - interval: 15s
    path: /metrics
    port: http 
  namespaceSelector:
    matchNames:
    - default
