replicaCount: 2

image:
  repository: pmagaz/rs-cpu-service 
  pullPolicy: Always 
  tag: "latest"

envSecretName: rust-auth-secrets

imagePullSecrets:
 - name: docker-credentials 

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  metadata:
    name: rs-cpu-service
    labels:
      app: rs-cpu-service

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/enable-cors: "true"
  hosts:
    - host: cluster.local
      paths:
      - path: /cpu
        pathType: Prefix
        backend:
          service:
            name: rs-cpu-service 
            port:
              number: 80 
  tls: []

resources:
  requests:
  cpu: 100m
  #memory: 128Mi
  #limits:
  #  cpu: 100m
  #  memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}
